### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by xlpppp** [mcoo/qqwry#1]
清理 缓存文件
未找到数据库文件，直接下载最新版本
开始更新
下载地址为:https://www.cz88.net/soft/rdJ8fn-2023-02-08.zip
下载完成，保存为qqwry.tmp
开始解压qqwry.dat
Error: rename tmp/app/qqwry.dat qqwry.dat: no such file or directory

怀疑是下载失败？
直接wget https://www.cz88.net/soft/rdJ8fn-2023-02-08.zip能下载到

**Comment by mcoo** [comment]
下载已经完成了，问题出现在解压的时候，问一下你的系统环境是什么？
还有innoextract的版本，你可以通过 
```
innoextract -v
```
看到

**Comment by xlpppp** [comment]
innoextract 1.9
Extracts installers created by Inno Setup 1.2.10 to 6.0.5

**Comment by mcoo** [comment]
已经修复完成了 可以从 [release](https://github.com/mcoo/qqwry/releases/tag/v0.0.1) 下载
